AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ImageProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8  # or whatever Python version you're using
      CodeUri: .
      Events:
        Api:
          Type: Api
          Properties:
            Path: /image-process
            Method: POST